const toolProficiencies = {
    0: "Alchemist's supplies",
    1: "Brewer's supplies",
    2: "Calligrapher's supplies",
    3: "Carpenter's tools",
    4: "Cartographer's tools",
    5: "Cobbler's tools",
    6: "Cook's utensils",
    7: "Glassblower's tools",
    8: "Jeweler's tools",
    9: "Leatherworker's tools",
    10: "Mason's tools",
    11: "Painter's supplies",
    12: "Potter's tools",
    13: "Smith's tools",
    14: "Tinker's tools",
    15: "Weaver's tools",
    16: "Woodcarver's tools",
    17: "Disguise Kit",
    18: "Forgery kit",
    19: "Herbalism kit",
    20: "Navigator's tools",
    21: "Poisoner's kit",
    22: "Thieves' tools",
    23: "Vehicles (land or water)",
    24: "Dice set",
    25: "Dragonchess set",
    26: "Playing card set",
    27: "Three-Dragon Ante set",
    28: "Bagpipes",
    29: "Drum",
    30: "Dulcimer",
    31: "Flute",
    32: "Lute",
    33: "Lyre",
    34: "Horn",
    35: "Pan flute",
    36: "Shawm",
    37: "Viol"
}